### PR TITLE
to test

### PR DESCRIPTION
**Pull request by hansieodendaal**
@anselld , this is how a pull request will look. 

Some test comment: `Notice in Markdown an open line between paragraphs will mean a new paragraph, otherwise it will be appended to the previous one.  Editors like Typora takes cares of this, inserting an additional newline when starting a new paragraph.`

You can squash-merge the pull request on your side if you are happy with the changes. So I would have performed the editing, you would just have accepted and merged it in.

### CODE REVIEW

**Comment by hansieodendaal** [comment]
Select 'Files changed' tab to see raw text changes, and then View to see the final product

**Comment by hansieodendaal** [comment]
So @anselld the exercise here was to add suggested changes to your README file, to see how review comments can be suggested and accepted. You closed this pull request without merging the changes in. Intentional?

**Comment by anselld** [comment]
No, unintentional. I thought I had merged it. Please try again and see. How could I check on my side?

**Comment by anselld** [comment]
I don't have a README-mdbook-link file (I see it is in the screen grab on page 3 of the email you sent me on 17 October. Please let me know how to insert it - thanks.

**Pull request closed without merging**
